tmgmt.translator.settings.textmaster:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    textmaster_service_url:
      type: string
      label: Lilt API url
    textmaster_api_key:
      type: string
      label: Lilt API key
    textmaster_api_secret:
      type: string
      label: Lilt API secret
