tmgmt.translator.settings.lilt:
  type: mapping
  mapping:
    lilt_service_url:
      type: string
      label: Lilt API URL
    lilt_api_key:
      type: string
      label: Lilt API key
    lilt_app_url:
      type: string
      label: Lilt App URL
    lilt_log_api:
      type: boolean
      label: Lilt API logging
    lilt_pretranslation:
      type: string
      label: Lilt Pretranslation
    lilt_auto_accept:
      type: boolean
      label: Lilt Auto-accept
    lilt_config_id:
      type: integer
      label: Lilt Config ID
