tmgmt.translator.settings.textmaster:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    textmaster_service_url:
      type: string
      label: TextMaster API url
    textmaster_api_key:
      type: string
      label: TextMaster API key
    textmaster_api_secret:
      type: string
      label: TextMaster API secret
